language: rust
rust:
  - stable
#  - beta
#  - nightly
cache: cargo
services:
  - postgresql
addons:
  postgresql: "9.6"
#matrix:
#  allow_failures:
#    - rust: nightly
#  fast_finish: true
env:
  BIGNEON_DB: bigneon
  DATABASE_URL: postgres://postgres@localhost/bigneon

before_script:
  - ./scripts/init.sh
