language: rust
rust:
  - stable
#  - beta
#  - nightly
cache: cargo
services:
  - postgresql
addons:
  postgresql: "9.6"

#matrix:
#  allow_failures:
#    - rust: nightly
#  fast_finish: true
env:
  BIGNEON_DB: bigneon
  DATABASE_URL: postgres://postgres@localhost/bigneon
  TEST_DATABASE_URL: postgres://postgres:password123@localhost/bigneon_test
  TEST_DATABASE_ADMIN_URL: postgres://postgres:password123@localhost/bigneon_test

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup component add rustfmt-preview
  - ./scripts/init-test.sh

script:
  - cargo fmt --all -- --check
  - cargo test
